routes/web.php
<?php

use App\Http\Controllers\CommentContrroler;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('user')->middleware('auth')->group(function () {
    Route::resource('post', PostController::class);
    Route::get('/like/{post}', [PostController::class, 'likePost'])->name('like-post');
    Route::get('/get-posts', [PostController::class, 'getPostsAjax'])->name('get-posts');
    Route::post('/store-comment/{post}', [CommentContrroler::class, 'store'])->name('store-comment');
    Route::get('hashtag-posts/{tag}', [PostController::class, 'HashTagsPosts'])->name('hashtag-posts');
});

app/Models/Post.php
<?php

namespace App\Models;

use Carbon\Carbon;
use App\Models\User;
use App\Models\HashTag;
use App\Traits\HasFile;
use App\Traits\HasComment;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Post extends Model
{
    use HasFactory;
    use HasFile;
    use HasComment;

    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function likes()
    {
        return $this->belongsToMany(User::class, 'post_likes', 'post_id', 'user_id');
    }

    public function getTimeAttribute()
    {
        if (Carbon::parse($this->created_at)->diffInSeconds() < 60) {
            $x = Carbon::parse($this->created_at)->diffInSeconds();
            return $x = 'Just now';
        } elseif (Carbon::parse($this->created_at)->diffInMinutes() < 60) {
            return Carbon::parse($this->created_at)->diffInMinutes() . ' minutes ago';
        } elseif (Carbon::parse($this->created_at)->diffInMinutes() < 720) {
            return Carbon::parse($this->created_at)->diffInHours() . ' hours ago';
        } elseif (Carbon::parse($this->created_at)->diffInMinutes() > 720 && Carbon::parse($this->created_at)->diffInMinutes() < 1440) {
            $x = Carbon::parse($this->created_at)->diffInMinutes();
            return $x = 'Today';
        } else {
            return Carbon::parse($this->created_at)->diffInDays() . ' days ago';
        }
    }

    public function getLikersAvatarAttribute()
    {
        $likersAvatar = [];
        $likers = $this->likes()->limit(4)->select('name')->get();
        foreach ($likers as $liker) {
            $likersAvatar[] = substr($liker->name, 0, 1);
        }
        return $likersAvatar;
    }

    public function tags()
    {
        return $this->belongsToMany(HashTag::class, 'post_hash', 'post_id', 'hash_tag_id');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\HashTag;
use App\Services\PostService;
use App\Traits\ResponsesJSON;
use App\Http\Requests\StorePostRequest;
use App\Http\Requests\UpdatePostRequest;

class PostController extends Controller
{
    use ResponsesJSON;

    protected $postService;

    public function __construct(PostService $postService)
    {
        $this->postService = $postService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = $this->postService->index();
        return view('post.index', ['posts' => $posts]);
    }

    public function getPostsAjax()
    {
        $posts = $this->postService->index();
        return $this->json(view('post.posts', ['posts' => $posts])->toHtml());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $view = view('post.create')->toHtml();
        return $this->json($view);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StorePostRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePostRequest $request)
    {
        $data = $request->all();
        $post = $this->postService->store($data);
        return $this->json(view('post.single_post', ['post' => $post])->toHtml());
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdatePostRequest  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        if (auth()->user()->id == $post->user_id) {
            $post->delete();
        }
        return redirect(route('post.index'));
    }

    public function likePost(Post $post)
    {
        $like = $this->postService->likePost($post);
        return $this->json(count($post->likes), $like);
    }

    public function hashTagsPosts(HashTag $tag)
    {
        $posts = $tag->posts;
        return $this->json(view('post.posts', ['posts' => $posts])->toHtml());
    }
}

resources/views/post/create.blade.php
<div class="row justify-content-center mt-2">
    <div class="col-8">
        <div class="form-group">
            <form action="{{ route('post.store') }}" method="POST" id="store-post" enctype="multipart/form-data">
                @csrf
                <div class="mb-3">
                    <p>Title:</p>
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <div class="mb-3">
                    <p>Description:</p>
                    <textarea name="description" class="form-control" id="description" cols="30" rows="10"></textarea>
                </div>
                <div id="hash-tag">
                    <div class="row" id="1">
                        <div class="col-10">
                            <div class="mb-3">
                                <p>Hash Tags:</p>
                                <input type="text" name="hashTags[1]" id="" class="form-control">
                            </div>
                        </div>
                        <div class="col-2">
                            <button type="button" class="btn btn-danger btn-delete" data-row-id="1">Remove</button>
                        </div>
                    </div>
                </div>
                <div class="mb-3">
                    <button type="button" class="btn btn-info" id="btn-add-hash">Add</button>
                </div>
                <div class="mb-3">
                    <p>Photo</p>
                    <input type="file" name="file" id="file">
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Post</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/post/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        {{-- start tabs --}}
        <ul class="nav nav-tabs justify-content-center" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="my-posts" data-url="{{ route('get-posts') }}" data-bs-toggle="tab"
                    data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">My
                    Posts</button>
            </li>
        </ul>
        {{-- end tabs --}}
        <div class="row mt-3">
            <div class="col-12">
                <button type="button" id="btn-add" data-url="{{ route('post.create') }}" class="btn btn-success">Add
                    {{ !count($posts) ? 'your first' : '' }} post</button>
            </div>
        </div>

        {{-- start content --}}
        <div id="my-content">
            @include('post.posts', ['posts' => $posts])
        </div>
    </div>
@endsection
@section('js')
    <script>
        let page = 1;
        $(document).on('click', '#my-posts', function() {
            getPosts(1, $(this).data('url'), 'empty');
            paginate = true;
        })

        function getPosts(page = 1, url, flag) {
            $.ajax({
                type: 'GET',
                url: url + '?page=' + page,
                success: function(res) {
                    if (flag == 'empty') {
                        $('#my-content').empty();
                        $('#my-content').html(res.data);
                    } else {
                        $('#my-content').append(res.data);
                    }
                }
            })
        }

        $(window).scroll(function() {
            if ($(window).scrollTop() + $(window).height() == $(document).height() && paginate) {
                page = ++page;
                getPosts(page, '{{ route('get-posts') }}', 'append');
            }
        });
    </script>
@endsection

resources/views/post/posts.blade.php
@foreach ($posts as $post)
    @include('post.single_post')
@endforeach

resources/views/post/single_post.blade.php
<section class="hero">
    <div class="container">
        <div class="row">

            <div class="col-lg-6 offset-lg-3">

                <div class="cardbox shadow-lg bg-white">

                    <div class="cardbox-heading">
                        <!-- START dropdown-->
                        <div class="dropdown float-right">
                            <div class="dropdown-menu dropdown-scale dropdown-menu-right" role="menu"
                                style="position: absolute; transform: translate3d(-136px, 28px, 0px); top: 0px; left: 0px; will-change: transform;">
                                <a class="dropdown-item" href="#">Hide post</a>
                                <a class="dropdown-item" href="#">Stop following</a>
                                <a class="dropdown-item" href="#">Report</a>
                            </div>
                        </div>
                        <!--/ dropdown -->
                        <div class="media m-0">
                            <div class="d-flex mr-3">
                                <button
                                    class="rounded-circle btn btn-sm btn-dark">{{ substr($post->user->name, 0, 1) }}</button>
                            </div>
                            <div class="media-body">
                                <p class="m-0">{{ $post->user->name }}</p>
                                {{-- <small><span><i class="icon ion-md-pin"></i> Nairobi, Kenya</span></small> --}}
                                <small><span><i class="icon ion-md-time"></i> {{ $post->time }}</span></small>
                            </div>
                            @if (auth()->user()->id == $post->user->id)
                                <div>
                                    <form action="{{ route('post.destroy', $post->id) }}" method="POST"
                                        id="form-delete">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger">Delete</button>

                                    </form>
                                </div>
                            @endif

                        </div>

                        <!--/ media -->
                    </div>
                    @if (count($post->tags))
                        <div class="cardbox-body">
                            <ul class="">
                                @foreach ($post->tags as $tag)
                                    <li class="border-0" style="display:inline">
                                        <button data-href="{{ route('hashtag-posts', $tag->id) }}" class="btn btn-link p-0 hash-tag">#{{ $tag->tag }}</button>
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    @if (count($post->files))
                        <!--/ cardbox-heading -->
                        <div class="cardbox-item">
                            <img class="img-fluid" src="/storage/{{ $post->files->first()->path }}" alt="Image">
                        </div>
                    @endif
                    {{-- cardbox body --}}
                    <div class="cardbox-body">
                        <h2>{{ $post->title }}</h2>
                        <p>{{ $post->description }}</p>
                    </div>
                    {{-- cardbox body --}}
                    <!--/ cardbox-item -->
                    <div class="cardbox-base">
                        <ul>
                            {{-- <li><a><i class="fa fa-thumbs-up"></i></a></li> --}}
                            @foreach ($post->LikersAvatar as $item)
                                <li>
                                    <button class="rounded-circle btn btn-sm btn-danger">{{ $item }}</button>
                                </li>
                            @endforeach
                            <li><a><span id="like-count">{{ count($post->likes) }} Likes</span></a></li>
                        </ul>
                        <ul class="float-right">
                            <li><a><i class="fa fa-comments">Comments</i></a></li>
                            <li><a><em class="mr-5 comments-count">{{ count($post->comments) }}</em></a></li>
                        </ul>
                        <table class="table table-borderd mb-0 text-center">
                            <tr>
                                <td>
                                    <button type="button"
                                        class="btn like {{ $post->likes()->where('user_id', auth()->user()->id)->first()? 'btn-primary': '' }}"
                                        id="like" data-url="{{ route('like-post', $post->id) }}">Like</button>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <!--/ cardbox-base -->
                    <div class="cardbox-body pb-0" id="comments" style="overflow-y: scroll; max-height:100px;">
                        @foreach ($post->comments as $comment)
                            <p>{{ $comment->comment }}</p>
                        @endforeach
                    </div>
                    <div class="cardbox-comments mt-5">
                        {{-- <span class="comment-avatar float-left">
                            <a href=""><img class="rounded-circle"
                                    src="http://www.themashabrand.com/templates/bootsnipp/post/assets/img/users/6.jpg"
                                    alt="..."></a>
                        </span> --}}
                        <form action="{{ route('store-comment', $post->id) }}" id="form-comment" method="POST"
                            class="">
                            @csrf
                            <div class="search">
                                <input placeholder="Write a comment" name="comment" type="text">
                                <button type="submit" class="btn btn-primary">comment</button>
                            </div>
                        </form>
                        <!--/. Search -->
                    </div>
                    <!--/ cardbox-like -->

                </div>
                <!--/ cardbox -->

            </div>
            <!--/ col-lg-6 -->
            <!--/ col-lg-3 -->

        </div>
        <!--/ row -->
    </div>
    <!--/ container -->
</section>